version: '3.8'

services:
  redis:
    image: ${REDIS_IMAGE}
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - taranet

  backend:
    image: ${DOCKER_IMAGE}:${IMAGE_TAG}
    container_name: tara_backend_dev
    restart: always
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      - backend_logs:/app/logs
    command: >
      gunicorn Tara.wsgi:application
      --bind 0.0.0.0:8000
      --workers 2
      --access-logfile /app/logs/access.log
      --error-logfile /app/logs/error.log
    depends_on:
      - redis
    networks:
      - taranet
  db:
    image: ${POSTGRES_IMAGE}
    container_name: tara_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - taranet

  celery_worker:
    image: ${DOCKER_IMAGE}:${IMAGE_TAG}
    container_name: celery_worker
    command: celery -A Tara worker --loglevel=info --pool=solo
    depends_on:
      - redis
    restart: always
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=Tara.settings.default               # ✅ Important
    env_file:
      - .env
    networks:
      - taranet

  celery_beat:
    image: ${DOCKER_IMAGE}:${IMAGE_TAG}
    container_name: celery_beat
    command: celery -A Tara beat --loglevel=info
    depends_on:
      - redis
    restart: always
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=Tara.settings.default               # ✅ Important
    env_file:
      - .env
    networks:
      - taranet

volumes:
  backend_logs:
  db_data:

networks:
  taranet:
    driver: bridge
